name: Build & Deploy myapp
on: 
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Unit Tests
        run: mvn -B test --file app.js
      - name: Build app
        run: mvn -B package --file app.js
